#!/bin/bash
#By shell.e00750..

# get ip address for gateway.
ip="tmp/gateway.txt"
ipgateways=`cat $ip`
for ip_gateway in $ipgateways; do
        echo "$ip_gateway"
done

# get network maps.
n="tmp/network_blocks.txt"
network_maps=`cat $n`
for network_map in $network_maps; do
        echo "$network_map"
done

# scan map
#nmap 192.168.0.0/24 -sT -p 22,23,139,1433,3306,3389,5432,9999,59777 |  awk '/^Nmap scan report/{cHost=$5;}
#----------------------------------------------------------------------------------------------------------

nmap "$ip_gateway"/"$network_map" -sT -p 389,1433,1434,1583,3306,3050,3351,5432,6446,6447,6448,6449,33060,33061 | awk '/^Nmap scan report/{cHost=$5;}
       /open/ { split($1,a,"/"); result[cHost][a[1]]=""}
       END {
       for (i in result) {
         printf i;
         for (j in result[i])
           printf ",%s", j ;
         print ""} }' |   sed -e 's/,/':UP'\  'TCP:' ''/'
